name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    if: contains(github.event.head_commit.message, '[NOBUILD]') == false
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v1
        with:
          java-version: openjdk11
          architecture: x64
      - name: Package
        run: mvn -B verify
      